# Generated by Django 3.1.4 on 2020-12-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharefree', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shares',
            new_name='Share',
        ),
    ]
